-- AirTrack Data Pack - Sri Lanka
-- Source: Civil Aviation Authority of Sri Lanka
-- Civil Aircraft Registered in Sri Lanka as at 11.03.2026
-- Fields retained: registration, hexcode, aircraftmanufacturer, aircraftmodel, operatorname.

CREATE TABLE IF NOT EXISTS sri_lanka (
    registration VARCHAR(10) NOT NULL PRIMARY KEY,
    hexcode VARCHAR(10),
    aircraftmanufacturer VARCHAR(100),
    aircraftmodel VARCHAR(50),
    msn VARCHAR(50),
    maxtakeoffweight INT,
    enginecount INT,
    enginemanufacturer VARCHAR(100),
    enginetype VARCHAR(50),
    enginemodel VARCHAR(50),
    fueltype VARCHAR(50),
    registrationtype VARCHAR(50),
    registeredowner VARCHAR(150),
    registeredownercountry VARCHAR(50),
    operatorname VARCHAR(150),
    operatorcountry VARCHAR(50),
    firstregistrationdate DATE,
    airframe VARCHAR(100),
    propmanu VARCHAR(100),
    propmodel VARCHAR(50),
    typecert VARCHAR(50),
    countrymanu VARCHAR(50),
    yearmanu INT,
    icaotypedesig VARCHAR(10)
);

INSERT INTO sri_lanka (
    registration,
    hexcode,
    aircraftmanufacturer,
    aircraftmodel,
    operatorname
) VALUES
('4R-ABL', NULL, 'AIRBUS', 'A320-232', 'SriLankan Airlines Ltd.'),
('4R-ABM', NULL, 'AIRBUS', 'A320-214', 'SriLankan Airlines Ltd.'),
('4R-ABN', NULL, 'AIRBUS', 'A320-214', 'SriLankan Airlines Ltd.'),
('4R-ABO', NULL, 'AIRBUS', 'A320-214', 'SriLankan Airlines Ltd.'),
('4R-ABS', NULL, 'AIRBUS', 'A320-232', 'SriLankan Airlines Ltd'),
('4R-ABT', NULL, 'AIRBUS', 'A320-232', 'SriLankan Airlines Ltd'),
('4R-MRE', NULL, 'AIRBUS', 'A320-232', 'SriLankan Airlines Ltd'),
('4R-ALH', NULL, 'AIRBUS', 'A330-243', 'SriLankan Airlines Ltd.'),
('4R-ALL', NULL, 'AIRBUS', 'A330-343', 'SriLankan Airlines Ltd'),
('4R-ALM', NULL, 'AIRBUS', 'A330-343', 'SriLankan Airlines Ltd'),
('4R-ALN', NULL, 'AIRBUS', 'A330-343', 'SriLankan Airlines Ltd'),
('4R-ALO', NULL, 'AIRBUS', 'A330-343', 'SriLankan Airlines Ltd'),
('4R-ALP', NULL, 'AIRBUS', 'A330-343', 'SriLankan Airlines Ltd'),
('4R-ALQ', NULL, 'AIRBUS', 'A330-343', 'SriLankan Airlines Ltd'),
('4R-ALR', NULL, 'AIRBUS', 'A330-343', 'SriLankan Airlines Ltd'),
('4R-ALS', NULL, 'AIRBUS', 'A330-243', 'SriLankan Airlines Ltd'),
('4R-ALT', NULL, 'AIRBUS', 'A330-243', 'SriLankan Airlines Ltd.'),
('4R-ANA', NULL, 'AIRBUS', 'A320-251N', 'SriLankan Airlines Ltd.'),
('4R-ANB', NULL, 'AIRBUS', 'A320-251N', 'SriLankan Airlines Ltd.'),
('4R-ANC', NULL, 'AIRBUS', 'A321-251N', 'SriLankan Airlines Ltd.'),
('4R-AND', NULL, 'AIRBUS', 'A321-251N', 'SriLankan Airlines Ltd.'),
('4R-ANE', NULL, 'AIRBUS', 'A321-251N', 'SriLankan Airlines Ltd.'),
('4R-ANF', NULL, 'AIRBUS', 'A321-251N', 'SriLankan Airlines Ltd'),
('4R-EXQ', NULL, 'AIRBUS', 'A320-232', 'Fits Aviation (Pvt) Ltd'),
('4R-EXR', NULL, 'AIRBUS', 'A320-232', 'Fits Aviation (Pvt) Ltd'),
('4R-EXS', NULL, 'AIRBUS', 'A320-232', 'Fits Aviation (Pvt) Ltd'),
('4R-CAE', NULL, 'CESSNA', '208 (Caravan)', 'Saffron Aviation (Pvt) Ltd'),
('4R-CAF', NULL, 'CESSNA', '208 (Caravan)', 'Saffron Aviation (Pvt) Ltd.'),
('4R-CAG', NULL, 'CESSNA', '208B', 'Saffron Aviation (Pvt) Ltd.'),
('4R-DPA', NULL, 'CESSNA', '208B', 'DP Aviation (Pvt) Ltd'),
('4R-MSS', NULL, 'AIRBUS HELICOPTER', 'AS350 B3', 'Senok Aviation (Pvt) Ltd'),
('4R-MVS', NULL, 'AIRBUS HELICOPTER', 'AS350 B3', 'Senok Aviation (Pvt) Ltd'),
('4R-FAB', NULL, 'CESSNA', '152', 'Flying Angel’s Flight Academy'),
('4R-FAC', NULL, 'CESSNA', '150 J', 'Flying Angel’s Flight Academy'),
('4R-ADI', NULL, 'CESSNA', '172M', 'Flying Angel’s Flight Academy'),
('4R-DRA', NULL, 'CESSNA', '152', 'Redbird Aviation (Pvt) Ltd'),
('4R-DAD', NULL, 'CESSNA', '152', 'Redbird Aviation (Pvt) Ltd'),
('4R-DLJ', NULL, 'CESSNA', '152', 'Red Bird Aviation (Pvt) Ltd'),
('4R-DOM', NULL, 'CESSNA', '152', 'Redbird Aviation (Pvt) Ltd'),
('4R-DRM', NULL, 'CESSNA', '172 R', 'Redbird Aviation (Pvt) Ltd'),
('4R-SRD', NULL, 'GIPPES AERO', 'GA 8', 'Lakwin Aviation (Pvt) Ltd'),
('4R-SJA', NULL, 'PIPER SENECA', 'PA 34-200 T', 'Lakwin Aviation (Pvt) Ltd'),
('4R-LWB', NULL, 'CESSNA', '152', 'Lakwin Aviation (Pvt) Ltd'),
('4R-LWC', NULL, 'CESSNA', '152', 'Lakwin Aviation (Pvt) Ltd'),
('4R-LWR', NULL, 'CESSNA', '152', 'Lakwin Aviation (Pvt) Ltd'),
('4R-ASK', NULL, 'ROBINSON', 'R 66', 'Lakwin Aviation (Pvt) Ltd'),
('4R-MDA', NULL, 'CESSNA', '152', 'Openskies Flight Training (Pvt) Ltd.'),
('4R-MDB', NULL, 'CESSNA', '152', 'Openskies Flight Training (Pvt) Ltd.'),
('4R-MDC', NULL, 'CESSNA', '152', 'Openskies Flight Training (Pvt) Ltd.'),
('4R-MDD', NULL, 'CESSNA', '172R', 'Openskies Flight Training (Pvt) Ltd.'),
('4R-MDE', NULL, 'PIPER CHEROKEE', 'PA28-140', 'Openskies Flight Training (Pvt) Ltd.'),
('4R-MDF', NULL, 'PIPER CHEROKEE', 'PA-28-140', 'Openskies Flight Training (Pvt) Ltd.'),
('4R-MDG', NULL, 'PIPER CHEROKEE', 'PA-28-140', 'Openskies Flight Training (Pvt) Ltd.'),
('4R-ENC', NULL, 'PIPER', 'PA 34-200T', 'Openskies Flight Training (Pvt) Ltd.'),
('4R-SAS', NULL, 'PIPER', 'PA 34-200T', 'Fly Southern (Pvt) Ltd'),
('4R-HRA', NULL, 'CESSNA', '172 RG', 'Fly Southern (Pvt) Ltd'),
('4R-FSA', NULL, 'CESSNA', '172 N', 'Fly Southern (Pvt) Ltd'),
('4R-RSW', NULL, 'CESSNA', '172', 'Fly Southern (Pvt) Ltd'),
('4R-SAB', NULL, 'CESSNA', '152', 'Skyline Aviation (Pvt) Ltd'),
('4R-SAY', NULL, 'CESSNA', '152', 'Skyline Aviation (Pvt) Ltd'),
('4R-SAZ', NULL, 'CESSNA', '152', 'Skyline Aviation (Pvt) Ltd'),
('4R-ASE', NULL, 'PIPER', 'PA 38-112', 'Sakurai Aviation Ltd'),
('4R-ASJ', NULL, 'PIPER', 'PA-38-112', 'Sakurai Aviation Ltd'),
('4R-WRM', NULL, 'PIPER', 'PA-34-220T', 'Sakurai Aviation Ltd'),
('4R-ACJ', NULL, 'CESSNA', '152', 'Asian Aviation Centre (Pvt) Ltd.'),
('4R-ACV', NULL, 'CESSNA', '152', 'Asian Aviation Centre (Pvt) Ltd.'),
('4R-ACE', NULL, 'PIPER', 'PA-34', 'Asian Aviation Centre (Pvt) Ltd.'),
('4R-CSM', NULL, 'AIRBUS HELICOPTER', 'EC120B', 'Chandika Viranjith Thambugala'),
('4R-CVT', NULL, 'AIRBUS HELICOPTER', 'EC130B4', 'Chandika Viranjith Thambugala'),
('4R-HTN', NULL, 'XIAN', 'MA 60', 'Helitours (Pvt) Ltd'),
('4R-HTO', NULL, 'XIAN', 'MA 60', 'Helitours (Pvt) Ltd'),
('4R-ISN', NULL, 'CAMERON - Hot Air Balloon', 'Z-210', 'Sun Rise Ballooning (Pvt) Ltd.'),
('4R-OSY', NULL, 'ULTRA MAGIC - Hot Air Balloon', 'N-355', 'Sun Rise Ballooning (Pvt) Ltd'),
('4R-ULR', NULL, 'LINDSTRAND - Hot Air Balloon', 'LBL-360A', 'Lanka Ballooning (Pvt) Ltd'),
('4R-BLN', NULL, 'LINDSTRAND - Hot Air Balloon', 'LBL-240A', 'Lanka Ballooning (Pvt) Ltd'),
('4R-SLB', NULL, 'ULTRA MAGIC - Hot Air Balloon', 'N-355', 'Lanka Ballooning (Pvt) Ltd'),
('4R-BTL', NULL, 'ULTRA MAGIC - Hot Air Balloon', 'N-355', 'Lanka Ballooning (Pvt) Ltd'),
('4R-DAC', NULL, 'AIRBUS HELICOPTER', 'EC 130 T2', 'Daya Aviation (Pvt) Ltd'),
('4R-LUV', NULL, 'CESSNA', '182 P', 'Capt. Anil Jayasinghe'),
('4R-RPG', NULL, 'CESSNA', '150', 'Ranjiv Priyantha Goonetilleke'),
('4R-DBS', NULL, 'CESSNA', '310R', 'Sriyantha Benedict Sirimanne'),
('4R-ELM', NULL, 'QUAD CITY', 'CHALLENGER II', 'Manage Kapila Gunaratne'),
('4R-KPW', NULL, 'QUAD CITY', 'CHALLENGER II', 'Kshemendra Pravin Weeratunge')
ON DUPLICATE KEY UPDATE
    hexcode = VALUES(hexcode),
    aircraftmanufacturer = VALUES(aircraftmanufacturer),
    aircraftmodel = VALUES(aircraftmodel),
    operatorname = VALUES(operatorname);
